AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./time
      AutoPublishAlias: timelive
      DeploymentPreference:
         Type: AllAtOnce
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  LoveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: indexOfLove.handler
      Runtime: nodejs6.10
      CodeUri: ./love
      AutoPublishAlias: lovelive
      DeploymentPreference:
         Type: AllAtOnce
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET

